#!/bin/sh

# Do a clean rebuild then create a .nupkg file using the version number
# generated by the build process.

msbuild HalideSharp.csproj /p:Configuration=Release /t:Clean
msbuild HalideSharp.csproj /p:Configuration=Release
nuget pack HalideSharp.nuspec -Version `cat version.txt` -MsbuildPath /usr/lib/mono/msbuild/15.0/bin/

